name: Build-and-deploy
on:
  push:

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
    
    - name: install git
      run: |
          sudo apt-get install git
          apt git --version
    - name: List Files
      run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
    
    # Checking out latest koji-gh-action-git-version
    - name: Checkout Git Version
      uses: actions/checkout@v3
      with:
        repository: DaniaErnest/git-tag
        token: ${{ secrets.GIT_TOKEN }}
        path: ./.github/actions/koji-gh-action-git-gitversion

        ref: main
        fetch-depth: 0
    - name: List Files After Checkout
      run: |
          pwd
          ls -a
        
    # Determining Version
    - name: Determine Version
      id: my-tag
      uses: ./.github/actions/koji-gh-action-git-gitversion



