name: Build-and-deploy
on:
  push:

jobs:
  build-tag:
    runs-on: ubuntu-20.04
    steps:
    
    - name: List Files
      run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
    
    # Checking out latest koji-gh-action-git-version
    - name: Checkout Git Version
      uses: actions/checkout@v2
      with:
        repository: DaniaErnest/git-tag
        token: ${{ secrets.GIT_TOKEN }}
        path: ./.github/actions/koji-gh-action-git-gitversion

        ref: main
        fetch-depth: 0
    - name: List Files After Checkout
      run: |
          pwd
          ls -la
          ls -a
    - name: install git
      run: |
          sudo apt-get install git
          sudo apt-get upgrade git
          git init
          apt git --version
          ls -a
    - name: Configure git to trust the workspace despite the different owner
      run:
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    # Determining Version
    - name: Determine Version
      id: my-tag
      uses: ./.github/actions/koji-gh-action-git-gitversion



