name: Build-and-deploy

on:
  push:

jobs:

  build-tag:
    name: Generate tag
    runs-on: ubuntu-latest
    steps:
    - name: upgrade git
      run: |-
        sudo apt-get update
        sudo apt-get install git

    # Checking out latest koji-gh-action-git-version
    - name: Checkout Git Version
      uses: actions/checkout@v3
      with:
        repository: DaniaErnest/git-tag
        token: ${{ secrets.GIT_TOKEN }}
        path: ./.github/actions/koji-gh-action-git-gitversion
        ref: v0
        fetch-depth: 0
        

    # Determining Version
    - name: Determine Version
      id: my-tag
      uses: ./.github/actions/koji-gh-action-git-gitversion
      with:
       token: ${{secrets.GIT_TOKEN }} }}



